### ISSUE TITLE
Issue test for glo boards

### ISSUE THREAD

**Issue by vitorrcunhaa** [AlexandreProenca/django-drf-file-generator#2]
Testando.
@AlexandreProenca olá.
Atualiza pro python3 aí genti boua.
[www.facebook.com](url)

- [primeiro de tudo ] 

- [segundamente ] 

- [ e por fim] 

```
public static void main(args[])
{
    System.out.prinln("Olá marte!");
}
```

**Comment by AlexandreProenca** [comment]
Hey Ho lets GO!

**Comment by AlexandreProenca** [comment]
Hey hope

**Comment by AlexandreProenca** [comment]
Gostei aprovado
